version: "3.7"

services:

  # Example job
  job:
    image: bam/base
    build:
      context: . 
      dockerfile: base.Dockerfile
    environment:
      - GCODE_FNAME=test.gcode
      - BAM_DEBUG=true
      - PROFILE=example_job_profile.csv
    command: "node dist/init-multiple-jobs.js"

  # Example machine
  machine:
    image: bam/base
    build:
      context: . 
      dockerfile: base.Dockerfile
    environment:
      - BAM_DEBUG=true
      - N_MACHINES=1
      - TIME_DILATION=0.01 # ratio for realtime (1 for realtime)
    command: "node dist/init-multiple-machines.js"

  # Example broker
  broker:
    image: bam/base
    build:
      context: . 
      dockerfile: base.Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      - DEBUG=true
      - N_PROCESSES=2
    command: "node dist/init-horizontal-broker.js"
  

